// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVAZRfXwB76R2HhwEGHJW8hNykq7ufOk',
    appId: '1:1004346991352:web:cb55f1e0d877363275110d',
    messagingSenderId: '1004346991352',
    projectId: 'fir-flutter-fe9dc',
    authDomain: 'fir-flutter-fe9dc.firebaseapp.com',
    storageBucket: 'fir-flutter-fe9dc.appspot.com',
    measurementId: 'G-3LDY92XF7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexkNgeqB6afbvJZQZnXCAHcnQT7RWErI',
    appId: '1:1004346991352:android:bb1d8f5c8a8731ec75110d',
    messagingSenderId: '1004346991352',
    projectId: 'fir-flutter-fe9dc',
    storageBucket: 'fir-flutter-fe9dc.appspot.com',
  );
}
